# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rusakUI.ui'
#
# Created: Thu May 09 13:59:28 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

#---------written by:----------------------
#-------Fauzan Syabana---------------------
#------zansyabana@gmail.com----------------
#Licensed under MIT License

from Qt import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 911)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_control)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.createControlGrp = QtWidgets.QGroupBox(self.tab_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createControlGrp.sizePolicy().hasHeightForWidth())
        self.createControlGrp.setSizePolicy(sizePolicy)
        self.createControlGrp.setMinimumSize(QtCore.QSize(0, 250))
        self.createControlGrp.setAcceptDrops(False)
        self.createControlGrp.setFlat(False)
        self.createControlGrp.setCheckable(False)
        self.createControlGrp.setObjectName("createControlGrp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.createControlGrp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(5, -1, 20, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.asJnt = QtWidgets.QRadioButton(self.createControlGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asJnt.sizePolicy().hasHeightForWidth())
        self.asJnt.setSizePolicy(sizePolicy)
        self.asJnt.setChecked(False)
        self.asJnt.setObjectName("asJnt")
        self.horizontalLayout.addWidget(self.asJnt)
        self.asCrv = QtWidgets.QRadioButton(self.createControlGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asCrv.sizePolicy().hasHeightForWidth())
        self.asCrv.setSizePolicy(sizePolicy)
        self.asCrv.setObjectName("asCrv")
        self.asCrv.setChecked(True)
        self.horizontalLayout.addWidget(self.asCrv)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.createControlGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.shp_CrossArrow = QtWidgets.QPushButton(self.groupBox)
        self.shp_CrossArrow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_CrossArrow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_CrossArrow.setAutoFillBackground(False)
        self.shp_CrossArrow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/crossArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_CrossArrow.setIcon(icon)
        self.shp_CrossArrow.setIconSize(QtCore.QSize(20, 20))
        self.shp_CrossArrow.setCheckable(False)
        self.shp_CrossArrow.setChecked(False)
        self.shp_CrossArrow.setFlat(True)
        self.shp_CrossArrow.setObjectName("shp_CrossArrow")
        self.gridLayout.addWidget(self.shp_CrossArrow, 1, 1, 1, 1)
        self.shp_Arrow = QtWidgets.QPushButton(self.groupBox)
        self.shp_Arrow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Arrow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Arrow.setAutoFillBackground(False)
        self.shp_Arrow.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/arrowDouble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Arrow.setIcon(icon1)
        self.shp_Arrow.setIconSize(QtCore.QSize(20, 20))
        self.shp_Arrow.setCheckable(False)
        self.shp_Arrow.setChecked(False)
        self.shp_Arrow.setFlat(True)
        self.shp_Arrow.setObjectName("shp_Arrow")
        self.gridLayout.addWidget(self.shp_Arrow, 1, 0, 1, 1)
        self.shp_Needle = QtWidgets.QPushButton(self.groupBox)
        self.shp_Needle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Needle.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Needle.setAutoFillBackground(False)
        self.shp_Needle.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/needle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Needle.setIcon(icon2)
        self.shp_Needle.setIconSize(QtCore.QSize(20, 20))
        self.shp_Needle.setCheckable(False)
        self.shp_Needle.setChecked(False)
        self.shp_Needle.setFlat(True)
        self.shp_Needle.setObjectName("shp_Needle")
        self.gridLayout.addWidget(self.shp_Needle, 1, 4, 1, 1)
        self.shp_ArrowBent = QtWidgets.QPushButton(self.groupBox)
        self.shp_ArrowBent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_ArrowBent.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_ArrowBent.setAutoFillBackground(False)
        self.shp_ArrowBent.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/arrowBent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_ArrowBent.setIcon(icon3)
        self.shp_ArrowBent.setIconSize(QtCore.QSize(20, 20))
        self.shp_ArrowBent.setCheckable(False)
        self.shp_ArrowBent.setChecked(False)
        self.shp_ArrowBent.setFlat(True)
        self.shp_ArrowBent.setObjectName("shp_ArrowBent")
        self.gridLayout.addWidget(self.shp_ArrowBent, 1, 2, 1, 1)
        self.shp_CrossArrowBent = QtWidgets.QPushButton(self.groupBox)
        self.shp_CrossArrowBent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_CrossArrowBent.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_CrossArrowBent.setAutoFillBackground(False)
        self.shp_CrossArrowBent.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/crossArrowBent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_CrossArrowBent.setIcon(icon4)
        self.shp_CrossArrowBent.setIconSize(QtCore.QSize(20, 20))
        self.shp_CrossArrowBent.setCheckable(False)
        self.shp_CrossArrowBent.setChecked(False)
        self.shp_CrossArrowBent.setFlat(True)
        self.shp_CrossArrowBent.setObjectName("shp_CrossArrowBent")
        self.gridLayout.addWidget(self.shp_CrossArrowBent, 1, 3, 1, 1)
        self.shp_Circle = QtWidgets.QPushButton(self.groupBox)
        self.shp_Circle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Circle.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Circle.setAutoFillBackground(False)
        self.shp_Circle.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Circle.setIcon(icon5)
        self.shp_Circle.setIconSize(QtCore.QSize(20, 20))
        self.shp_Circle.setCheckable(False)
        self.shp_Circle.setChecked(False)
        self.shp_Circle.setFlat(True)
        self.shp_Circle.setObjectName("shp_Circle")
        self.gridLayout.addWidget(self.shp_Circle, 0, 0, 1, 1)
        self.shp_Square = QtWidgets.QPushButton(self.groupBox)
        self.shp_Square.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Square.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Square.setAutoFillBackground(False)
        self.shp_Square.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Square.setIcon(icon6)
        self.shp_Square.setIconSize(QtCore.QSize(20, 20))
        self.shp_Square.setCheckable(False)
        self.shp_Square.setChecked(False)
        self.shp_Square.setFlat(True)
        self.shp_Square.setObjectName("shp_Square")
        self.gridLayout.addWidget(self.shp_Square, 0, 1, 1, 1)
        self.shp_Cross = QtWidgets.QPushButton(self.groupBox)
        self.shp_Cross.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Cross.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Cross.setAutoFillBackground(False)
        self.shp_Cross.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Cross.setIcon(icon7)
        self.shp_Cross.setIconSize(QtCore.QSize(20, 20))
        self.shp_Cross.setCheckable(False)
        self.shp_Cross.setChecked(False)
        self.shp_Cross.setFlat(True)
        self.shp_Cross.setObjectName("shp_Cross")
        self.gridLayout.addWidget(self.shp_Cross, 0, 4, 1, 1)
        self.shp_Sphere = QtWidgets.QPushButton(self.groupBox)
        self.shp_Sphere.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Sphere.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Sphere.setAutoFillBackground(False)
        self.shp_Sphere.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/sphere.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Sphere.setIcon(icon8)
        self.shp_Sphere.setIconSize(QtCore.QSize(20, 20))
        self.shp_Sphere.setCheckable(False)
        self.shp_Sphere.setChecked(False)
        self.shp_Sphere.setFlat(True)
        self.shp_Sphere.setObjectName("shp_Sphere")
        self.gridLayout.addWidget(self.shp_Sphere, 0, 2, 1, 1)
        self.shp_Box = QtWidgets.QPushButton(self.groupBox)
        self.shp_Box.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Box.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Box.setAutoFillBackground(False)
        self.shp_Box.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Box.setIcon(icon9)
        self.shp_Box.setIconSize(QtCore.QSize(20, 20))
        self.shp_Box.setCheckable(False)
        self.shp_Box.setChecked(False)
        self.shp_Box.setFlat(True)
        self.shp_Box.setObjectName("shp_Box")
        self.gridLayout.addWidget(self.shp_Box, 0, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.createControlGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.btn_createCtl = QtWidgets.QPushButton(self.createControlGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_createCtl.sizePolicy().hasHeightForWidth())
        self.btn_createCtl.setSizePolicy(sizePolicy)
        self.btn_createCtl.setObjectName("btn_createCtl")
        self.horizontalLayout_2.addWidget(self.btn_createCtl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.createControlGrp)
        self.colorGrp = QtWidgets.QGroupBox(self.tab_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorGrp.sizePolicy().hasHeightForWidth())
        self.colorGrp.setSizePolicy(sizePolicy)
        self.colorGrp.setObjectName("colorGrp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.colorGrp)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.col_purple = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_purple.sizePolicy().hasHeightForWidth())
        self.col_purple.setSizePolicy(sizePolicy)
        self.col_purple.setMinimumSize(QtCore.QSize(0, 15))
        self.col_purple.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_purple.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border: 0px;")
        self.col_purple.setText("")
        self.col_purple.setObjectName("col_purple")
        self.gridLayout_3.addWidget(self.col_purple, 0, 4, 1, 1)
        self.col_yellow = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_yellow.sizePolicy().hasHeightForWidth())
        self.col_yellow.setSizePolicy(sizePolicy)
        self.col_yellow.setMinimumSize(QtCore.QSize(0, 15))
        self.col_yellow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_yellow.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 0px;")
        self.col_yellow.setText("")
        self.col_yellow.setObjectName("col_yellow")
        self.gridLayout_3.addWidget(self.col_yellow, 0, 5, 1, 1)
        self.col_cyan = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_cyan.sizePolicy().hasHeightForWidth())
        self.col_cyan.setSizePolicy(sizePolicy)
        self.col_cyan.setMinimumSize(QtCore.QSize(0, 15))
        self.col_cyan.setStyleSheet("background-color: cyan;\n"
"border: 0px;")
        self.col_cyan.setText("")
        self.col_cyan.setObjectName("col_cyan")
        self.gridLayout_3.addWidget(self.col_cyan, 0, 3, 1, 1)
        self.col_blue = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_blue.sizePolicy().hasHeightForWidth())
        self.col_blue.setSizePolicy(sizePolicy)
        self.col_blue.setMinimumSize(QtCore.QSize(0, 15))
        self.col_blue.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border: 0px;")
        self.col_blue.setText("")
        self.col_blue.setObjectName("col_blue")
        self.gridLayout_3.addWidget(self.col_blue, 0, 1, 1, 1)
        self.col_green = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_green.sizePolicy().hasHeightForWidth())
        self.col_green.setSizePolicy(sizePolicy)
        self.col_green.setMinimumSize(QtCore.QSize(0, 15))
        self.col_green.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_green.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border: 0px;")
        self.col_green.setText("")
        self.col_green.setObjectName("col_green")
        self.gridLayout_3.addWidget(self.col_green, 0, 2, 1, 1)
        self.col_red = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_red.sizePolicy().hasHeightForWidth())
        self.col_red.setSizePolicy(sizePolicy)
        self.col_red.setMinimumSize(QtCore.QSize(0, 15))
        self.col_red.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_red.setAutoFillBackground(False)
        self.col_red.setStyleSheet("background-color:red;\n"
"border: 0px;")
        self.col_red.setText("")
        self.col_red.setDefault(False)
        self.col_red.setFlat(False)
        self.col_red.setObjectName("col_red")
        self.gridLayout_3.addWidget(self.col_red, 0, 0, 1, 1)
        self.col_white = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_white.sizePolicy().hasHeightForWidth())
        self.col_white.setSizePolicy(sizePolicy)
        self.col_white.setMinimumSize(QtCore.QSize(0, 15))
        self.col_white.setStyleSheet("background-color: white;\n"
"border: 0px;")
        self.col_white.setText("")
        self.col_white.setObjectName("col_white")
        self.gridLayout_3.addWidget(self.col_white, 1, 1, 1, 1)
        self.col_black = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_black.sizePolicy().hasHeightForWidth())
        self.col_black.setSizePolicy(sizePolicy)
        self.col_black.setMinimumSize(QtCore.QSize(0, 15))
        self.col_black.setStyleSheet("background-color: black;\n"
"border: 0px;")
        self.col_black.setText("")
        self.col_black.setObjectName("col_black")
        self.gridLayout_3.addWidget(self.col_black, 1, 0, 1, 1)
        self.col_blue2 = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_blue2.sizePolicy().hasHeightForWidth())
        self.col_blue2.setSizePolicy(sizePolicy)
        self.col_blue2.setMinimumSize(QtCore.QSize(0, 15))
        self.col_blue2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_blue2.setStyleSheet("background-color: blue;\n"
"border: 0px;")
        self.col_blue2.setText("")
        self.col_blue2.setObjectName("col_blue2")
        self.gridLayout_3.addWidget(self.col_blue2, 1, 2, 1, 1)
        self.col_green2 = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_green2.sizePolicy().hasHeightForWidth())
        self.col_green2.setSizePolicy(sizePolicy)
        self.col_green2.setMinimumSize(QtCore.QSize(0, 15))
        self.col_green2.setStyleSheet("background-color:rgb(61, 122, 90);\n"
"border: 0px;")
        self.col_green2.setText("")
        self.col_green2.setObjectName("col_green2")
        self.gridLayout_3.addWidget(self.col_green2, 1, 3, 1, 1)
        self.col_pink = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_pink.sizePolicy().hasHeightForWidth())
        self.col_pink.setSizePolicy(sizePolicy)
        self.col_pink.setMinimumSize(QtCore.QSize(0, 15))
        self.col_pink.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_pink.setStyleSheet("background-color:rgb(255, 85, 255);\n"
"border: 0px;")
        self.col_pink.setText("")
        self.col_pink.setObjectName("col_pink")
        self.gridLayout_3.addWidget(self.col_pink, 1, 4, 1, 1)
        self.col_brown = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_brown.sizePolicy().hasHeightForWidth())
        self.col_brown.setSizePolicy(sizePolicy)
        self.col_brown.setMinimumSize(QtCore.QSize(0, 15))
        self.col_brown.setStyleSheet("background-color: brown;\n"
"border: 0px;")
        self.col_brown.setText("")
        self.col_brown.setObjectName("col_brown")
        self.gridLayout_3.addWidget(self.col_brown, 1, 5, 1, 1)
        self.verticalLayout_4.addWidget(self.colorGrp)
        self.resizeGrp = QtWidgets.QGroupBox(self.tab_control)
        self.resizeGrp.setObjectName("resizeGrp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.resizeGrp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sizeX = QtWidgets.QCheckBox(self.resizeGrp)
        self.sizeX.setChecked(True)
        self.sizeX.setObjectName("sizeX")
        self.horizontalLayout_4.addWidget(self.sizeX)
        self.sizeY = QtWidgets.QCheckBox(self.resizeGrp)
        self.sizeY.setChecked(True)
        self.sizeY.setObjectName("sizeY")
        self.horizontalLayout_4.addWidget(self.sizeY)
        self.sizeZ = QtWidgets.QCheckBox(self.resizeGrp)
        self.sizeZ.setChecked(True)
        self.sizeZ.setObjectName("sizeZ")
        self.horizontalLayout_4.addWidget(self.sizeZ)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_resizeStep = QtWidgets.QLabel(self.resizeGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resizeStep.sizePolicy().hasHeightForWidth())
        self.label_resizeStep.setSizePolicy(sizePolicy)
        self.label_resizeStep.setObjectName("label_resizeStep")
        self.horizontalLayout_5.addWidget(self.label_resizeStep)
        self.sizeStepSpinBox = QtWidgets.QDoubleSpinBox(self.resizeGrp)
        self.sizeStepSpinBox.setDecimals(1)
        self.sizeStepSpinBox.setSingleStep(0.2)
        self.sizeStepSpinBox.setProperty("value", 1.2)
        self.sizeStepSpinBox.setObjectName("sizeStepSpinBox")
        self.horizontalLayout_5.addWidget(self.sizeStepSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.resizeSlider = QtWidgets.QSlider(self.resizeGrp)
        self.resizeSlider.setMinimum(-10)
        self.resizeSlider.setMaximum(10)
        self.resizeSlider.setTracking(True)
        self.resizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.resizeSlider.setInvertedAppearance(False)
        self.resizeSlider.setInvertedControls(False)
        self.resizeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.resizeSlider.setObjectName("resizeSlider")
        self.verticalLayout_5.addWidget(self.resizeSlider)
        self.verticalLayout_4.addWidget(self.resizeGrp)
        self.rotateGrp = QtWidgets.QGroupBox(self.tab_control)
        self.rotateGrp.setObjectName("rotateGrp")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rotateGrp)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_angle = QtWidgets.QLabel(self.rotateGrp)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_angle.setFont(font)
        self.label_angle.setObjectName("label_angle")
        self.horizontalLayout_9.addWidget(self.label_angle)
        self.angle_box = QtWidgets.QSpinBox(self.rotateGrp)
        self.angle_box.setMaximum(360)
        self.angle_box.setSingleStep(45)
        self.angle_box.setProperty("value", 90)
        self.angle_box.setObjectName("angle_box")
        self.horizontalLayout_9.addWidget(self.angle_box)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_rotateX = QtWidgets.QPushButton(self.rotateGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateX.sizePolicy().hasHeightForWidth())
        self.btn_rotateX.setSizePolicy(sizePolicy)
        self.btn_rotateX.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateX.setStyleSheet("background-color: rgb(255, 70, 70);\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateX.setObjectName("btn_rotateX")
        self.horizontalLayout_7.addWidget(self.btn_rotateX)
        self.btn_rotateY = QtWidgets.QPushButton(self.rotateGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateY.sizePolicy().hasHeightForWidth())
        self.btn_rotateY.setSizePolicy(sizePolicy)
        self.btn_rotateY.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateY.setStyleSheet("background-color: rgb(72, 216, 0);\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateY.setObjectName("btn_rotateY")
        self.horizontalLayout_7.addWidget(self.btn_rotateY)
        self.btn_rotateZ = QtWidgets.QPushButton(self.rotateGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateZ.sizePolicy().hasHeightForWidth())
        self.btn_rotateZ.setSizePolicy(sizePolicy)
        self.btn_rotateZ.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateZ.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateZ.setObjectName("btn_rotateZ")
        self.horizontalLayout_7.addWidget(self.btn_rotateZ)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.rotateGrp)
        self.mirrorGrp = QtWidgets.QGroupBox(self.tab_control)
        self.mirrorGrp.setObjectName("mirrorGrp")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mirrorGrp)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnMirrorX = QtWidgets.QPushButton(self.mirrorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMirrorX.sizePolicy().hasHeightForWidth())
        self.btnMirrorX.setSizePolicy(sizePolicy)
        self.btnMirrorX.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btnMirrorX.setFont(font)
        self.btnMirrorX.setStyleSheet("background-color: rgb(255, 70, 70);\n"
"color: white;\n"
"border: 0px;")
        self.btnMirrorX.setObjectName("btnMirrorX")
        self.horizontalLayout_6.addWidget(self.btnMirrorX)
        self.btn_mirrorY = QtWidgets.QPushButton(self.mirrorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mirrorY.sizePolicy().hasHeightForWidth())
        self.btn_mirrorY.setSizePolicy(sizePolicy)
        self.btn_mirrorY.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btn_mirrorY.setFont(font)
        self.btn_mirrorY.setStyleSheet("background-color: rgb(72, 216, 0);\n"
"color: white;\n"
"border: 0px;")
        self.btn_mirrorY.setObjectName("btn_mirrorY")
        self.horizontalLayout_6.addWidget(self.btn_mirrorY)
        self.btn_mirrorZ = QtWidgets.QPushButton(self.mirrorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mirrorZ.sizePolicy().hasHeightForWidth())
        self.btn_mirrorZ.setSizePolicy(sizePolicy)
        self.btn_mirrorZ.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btn_mirrorZ.setFont(font)
        self.btn_mirrorZ.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border: 0px;")
        self.btn_mirrorZ.setObjectName("btn_mirrorZ")
        self.horizontalLayout_6.addWidget(self.btn_mirrorZ)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.mirrorLRLabel = QtWidgets.QLabel(self.mirrorGrp)
        self.mirrorLRLabel.setObjectName("mirrorLRLabel")
        self.horizontalLayout_14.addWidget(self.mirrorLRLabel)
        self.mirrorLR_edit = QtWidgets.QLineEdit(self.mirrorGrp)
        self.mirrorLR_edit.setObjectName("mirrorLR_edit")
        self.horizontalLayout_14.addWidget(self.mirrorLR_edit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.verticalLayout_4.addWidget(self.mirrorGrp)
        self.zero_grp = QtWidgets.QGroupBox(self.tab_control)
        self.zero_grp.setObjectName("zero_grp")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.zero_grp)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_suffix = QtWidgets.QLabel(self.zero_grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_suffix.sizePolicy().hasHeightForWidth())
        self.label_suffix.setSizePolicy(sizePolicy)
        self.label_suffix.setMinimumSize(QtCore.QSize(100, 0))
        self.label_suffix.setObjectName("label_suffix")
        self.horizontalLayout_10.addWidget(self.label_suffix)
        self.suffix_edit = QtWidgets.QLineEdit(self.zero_grp)
        self.suffix_edit.setObjectName("suffix_edit")
        self.horizontalLayout_10.addWidget(self.suffix_edit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.suffix_label = QtWidgets.QLabel(self.zero_grp)
        self.suffix_label.setObjectName("suffix_label")
        self.horizontalLayout_11.addWidget(self.suffix_label)
        self.suffix_keep = QtWidgets.QRadioButton(self.zero_grp)
        self.suffix_keep.setChecked(True)
        self.suffix_keep.setObjectName("suffix_keep")
        self.horizontalLayout_11.addWidget(self.suffix_keep)
        self.suffix_delete = QtWidgets.QRadioButton(self.zero_grp)
        self.suffix_delete.setObjectName("suffix_delete")
        self.horizontalLayout_11.addWidget(self.suffix_delete)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.zero_btn = QtWidgets.QPushButton(self.zero_grp)
        self.zero_btn.setObjectName("zero_btn")
        self.verticalLayout_9.addWidget(self.zero_btn)
        self.verticalLayout_4.addWidget(self.zero_grp)
        self.tabWidget.addTab(self.tab_control, "")
        self.tab_mod = QtWidgets.QWidget()
        self.tab_mod.setObjectName("tab_mod")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_mod)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.text_mod = QtWidgets.QLabel(self.tab_mod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_mod.sizePolicy().hasHeightForWidth())
        self.text_mod.setSizePolicy(sizePolicy)
        self.text_mod.setMinimumSize(QtCore.QSize(50, 0))
        self.text_mod.setObjectName("text_mod")
        self.horizontalLayout_8.addWidget(self.text_mod)
        self.combo_mod = QtWidgets.QComboBox(self.tab_mod)
        self.combo_mod.setMinimumSize(QtCore.QSize(150, 0))
        self.combo_mod.setObjectName("combo_mod")
        self.horizontalLayout_8.addWidget(self.combo_mod)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.widget = QtWidgets.QWidget(self.tab_mod)
        self.widget.setMinimumSize(QtCore.QSize(0, 500))
        self.widget.setObjectName("widget")
        self.verticalLayout_8.addWidget(self.widget)
        self.tabWidget.addTab(self.tab_mod, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "R.U.S.A.K.", None))
        self.createControlGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Control Creator", None))
        self.asJnt.setText(QtWidgets.QApplication.translate("MainWindow", "as Joint", None))
        self.asCrv.setText(QtWidgets.QApplication.translate("MainWindow", "as Curve", None))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "QuickCreate", None))
        self.btn_createCtl.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None))
        self.colorGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Color Picker", None))
        self.resizeGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Resize", None))
        self.sizeX.setText(QtWidgets.QApplication.translate("MainWindow", "X", None))
        self.sizeY.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None))
        self.sizeZ.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None))
        self.label_resizeStep.setText(QtWidgets.QApplication.translate("MainWindow", "Step: ", None))
        self.rotateGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Rotate", None))
        self.label_angle.setText(QtWidgets.QApplication.translate("MainWindow", "Angle:", None))
        self.btn_rotateX.setText(QtWidgets.QApplication.translate("MainWindow", "X", None))
        self.btn_rotateY.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None))
        self.btn_rotateZ.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None))
        self.mirrorGrp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Mirror Controller", None))
        self.btnMirrorX.setText(QtWidgets.QApplication.translate("MainWindow", "X", None))
        self.btn_mirrorY.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None))
        self.btn_mirrorZ.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None))
        self.mirrorLRLabel.setText(QtWidgets.QApplication.translate("MainWindow", "LeftName, RightName:", None))
        self.mirrorLR_edit.setText(QtWidgets.QApplication.translate("MainWindow", "_L_,_R_", None))
        self.zero_grp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Zero Transform", None))
        self.label_suffix.setText(QtWidgets.QApplication.translate("MainWindow", "Suffix Name:", None))
        self.suffix_edit.setText(QtWidgets.QApplication.translate("MainWindow", "_RG", None))
        self.suffix_label.setText(QtWidgets.QApplication.translate("MainWindow", "Previous Suffix:", None))
        self.suffix_keep.setText(QtWidgets.QApplication.translate("MainWindow", "Keep", None))
        self.suffix_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None))
        self.zero_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Zero Transform", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_control), QtWidgets.QApplication.translate("MainWindow", "Controllers", None))
        self.text_mod.setText(QtWidgets.QApplication.translate("MainWindow", "Module:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mod), QtWidgets.QApplication.translate("MainWindow", "Modules", None))

# import icons_rc