# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\JanosMayaScripts\JanosMayaScript\scripts\RUSAK\rusakU2I_new2.ui'
#
# Created: Sat Nov 20 11:45:55 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 634)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_control)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QToolBox(self.tab_control)
        self.toolBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 200))
        self.toolBox.setMouseTracking(False)
        self.toolBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBox.setAcceptDrops(False)
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet("background-color:rgb(68, 68, 68)")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page_control = QtWidgets.QWidget()
        self.page_control.setGeometry(QtCore.QRect(0, 0, 258, 334))
        self.page_control.setObjectName("page_control")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_control)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(5, -1, 20, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.asJnt = QtWidgets.QRadioButton(self.page_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asJnt.sizePolicy().hasHeightForWidth())
        self.asJnt.setSizePolicy(sizePolicy)
        self.asJnt.setChecked(True)
        self.asJnt.setObjectName("asJnt")
        self.horizontalLayout.addWidget(self.asJnt)
        self.asCrv = QtWidgets.QRadioButton(self.page_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asCrv.sizePolicy().hasHeightForWidth())
        self.asCrv.setSizePolicy(sizePolicy)
        self.asCrv.setObjectName("asCrv")
        self.horizontalLayout.addWidget(self.asCrv)
        self.asReplace = QtWidgets.QRadioButton(self.page_control)
        self.asReplace.setObjectName("asReplace")
        self.horizontalLayout.addWidget(self.asReplace)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.page_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.shp_CrossArrow = QtWidgets.QPushButton(self.groupBox)
        self.shp_CrossArrow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_CrossArrow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_CrossArrow.setAutoFillBackground(False)
        self.shp_CrossArrow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/crossArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_CrossArrow.setIcon(icon)
        self.shp_CrossArrow.setIconSize(QtCore.QSize(20, 20))
        self.shp_CrossArrow.setCheckable(False)
        self.shp_CrossArrow.setChecked(False)
        self.shp_CrossArrow.setFlat(True)
        self.shp_CrossArrow.setObjectName("shp_CrossArrow")
        self.gridLayout.addWidget(self.shp_CrossArrow, 1, 1, 1, 1)
        self.shp_Arrow = QtWidgets.QPushButton(self.groupBox)
        self.shp_Arrow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Arrow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Arrow.setAutoFillBackground(False)
        self.shp_Arrow.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/arrowDouble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Arrow.setIcon(icon1)
        self.shp_Arrow.setIconSize(QtCore.QSize(20, 20))
        self.shp_Arrow.setCheckable(False)
        self.shp_Arrow.setChecked(False)
        self.shp_Arrow.setFlat(True)
        self.shp_Arrow.setObjectName("shp_Arrow")
        self.gridLayout.addWidget(self.shp_Arrow, 1, 0, 1, 1)
        self.shp_Needle = QtWidgets.QPushButton(self.groupBox)
        self.shp_Needle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Needle.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Needle.setAutoFillBackground(False)
        self.shp_Needle.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/needle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Needle.setIcon(icon2)
        self.shp_Needle.setIconSize(QtCore.QSize(20, 20))
        self.shp_Needle.setCheckable(False)
        self.shp_Needle.setChecked(False)
        self.shp_Needle.setFlat(True)
        self.shp_Needle.setObjectName("shp_Needle")
        self.gridLayout.addWidget(self.shp_Needle, 1, 4, 1, 1)
        self.shp_ArrowBent = QtWidgets.QPushButton(self.groupBox)
        self.shp_ArrowBent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_ArrowBent.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_ArrowBent.setAutoFillBackground(False)
        self.shp_ArrowBent.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/arrowBent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_ArrowBent.setIcon(icon3)
        self.shp_ArrowBent.setIconSize(QtCore.QSize(20, 20))
        self.shp_ArrowBent.setCheckable(False)
        self.shp_ArrowBent.setChecked(False)
        self.shp_ArrowBent.setFlat(True)
        self.shp_ArrowBent.setObjectName("shp_ArrowBent")
        self.gridLayout.addWidget(self.shp_ArrowBent, 1, 2, 1, 1)
        self.shp_CrossArrowBent = QtWidgets.QPushButton(self.groupBox)
        self.shp_CrossArrowBent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_CrossArrowBent.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_CrossArrowBent.setAutoFillBackground(False)
        self.shp_CrossArrowBent.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/crossArrowBent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_CrossArrowBent.setIcon(icon4)
        self.shp_CrossArrowBent.setIconSize(QtCore.QSize(20, 20))
        self.shp_CrossArrowBent.setCheckable(False)
        self.shp_CrossArrowBent.setChecked(False)
        self.shp_CrossArrowBent.setFlat(True)
        self.shp_CrossArrowBent.setObjectName("shp_CrossArrowBent")
        self.gridLayout.addWidget(self.shp_CrossArrowBent, 1, 3, 1, 1)
        self.shp_Circle = QtWidgets.QPushButton(self.groupBox)
        self.shp_Circle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Circle.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Circle.setAutoFillBackground(False)
        self.shp_Circle.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Circle.setIcon(icon5)
        self.shp_Circle.setIconSize(QtCore.QSize(20, 20))
        self.shp_Circle.setCheckable(False)
        self.shp_Circle.setChecked(False)
        self.shp_Circle.setFlat(True)
        self.shp_Circle.setObjectName("shp_Circle")
        self.gridLayout.addWidget(self.shp_Circle, 0, 0, 1, 1)
        self.shp_Square = QtWidgets.QPushButton(self.groupBox)
        self.shp_Square.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Square.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Square.setAutoFillBackground(False)
        self.shp_Square.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Square.setIcon(icon6)
        self.shp_Square.setIconSize(QtCore.QSize(20, 20))
        self.shp_Square.setCheckable(False)
        self.shp_Square.setChecked(False)
        self.shp_Square.setFlat(True)
        self.shp_Square.setObjectName("shp_Square")
        self.gridLayout.addWidget(self.shp_Square, 0, 1, 1, 1)
        self.shp_Cross = QtWidgets.QPushButton(self.groupBox)
        self.shp_Cross.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Cross.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Cross.setAutoFillBackground(False)
        self.shp_Cross.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Cross.setIcon(icon7)
        self.shp_Cross.setIconSize(QtCore.QSize(20, 20))
        self.shp_Cross.setCheckable(False)
        self.shp_Cross.setChecked(False)
        self.shp_Cross.setFlat(True)
        self.shp_Cross.setObjectName("shp_Cross")
        self.gridLayout.addWidget(self.shp_Cross, 0, 4, 1, 1)
        self.shp_Sphere = QtWidgets.QPushButton(self.groupBox)
        self.shp_Sphere.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Sphere.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Sphere.setAutoFillBackground(False)
        self.shp_Sphere.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/sphere.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Sphere.setIcon(icon8)
        self.shp_Sphere.setIconSize(QtCore.QSize(20, 20))
        self.shp_Sphere.setCheckable(False)
        self.shp_Sphere.setChecked(False)
        self.shp_Sphere.setFlat(True)
        self.shp_Sphere.setObjectName("shp_Sphere")
        self.gridLayout.addWidget(self.shp_Sphere, 0, 2, 1, 1)
        self.shp_Box = QtWidgets.QPushButton(self.groupBox)
        self.shp_Box.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Box.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Box.setAutoFillBackground(False)
        self.shp_Box.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Box.setIcon(icon9)
        self.shp_Box.setIconSize(QtCore.QSize(20, 20))
        self.shp_Box.setCheckable(False)
        self.shp_Box.setChecked(False)
        self.shp_Box.setFlat(True)
        self.shp_Box.setObjectName("shp_Box")
        self.gridLayout.addWidget(self.shp_Box, 0, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.page_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.btn_createCtl = QtWidgets.QPushButton(self.page_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_createCtl.sizePolicy().hasHeightForWidth())
        self.btn_createCtl.setSizePolicy(sizePolicy)
        self.btn_createCtl.setObjectName("btn_createCtl")
        self.horizontalLayout_2.addWidget(self.btn_createCtl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_15.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(145, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.toolBox.addItem(self.page_control, "")
        self.page_color = QtWidgets.QWidget()
        self.page_color.setGeometry(QtCore.QRect(0, 0, 258, 334))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.page_color.sizePolicy().hasHeightForWidth())
        self.page_color.setSizePolicy(sizePolicy)
        self.page_color.setObjectName("page_color")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_color)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.colorGrp = QtWidgets.QWidget(self.page_color)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(self.colorGrp.sizePolicy().hasHeightForWidth())
        self.colorGrp.setSizePolicy(sizePolicy)
        self.colorGrp.setMinimumSize(QtCore.QSize(0, 20))
        self.colorGrp.setObjectName("colorGrp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.colorGrp)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.col_purple = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_purple.sizePolicy().hasHeightForWidth())
        self.col_purple.setSizePolicy(sizePolicy)
        self.col_purple.setMinimumSize(QtCore.QSize(0, 15))
        self.col_purple.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_purple.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border: 0px;")
        self.col_purple.setText("")
        self.col_purple.setObjectName("col_purple")
        self.gridLayout_3.addWidget(self.col_purple, 0, 4, 1, 1)
        self.col_yellow = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_yellow.sizePolicy().hasHeightForWidth())
        self.col_yellow.setSizePolicy(sizePolicy)
        self.col_yellow.setMinimumSize(QtCore.QSize(0, 15))
        self.col_yellow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_yellow.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 0px;")
        self.col_yellow.setText("")
        self.col_yellow.setObjectName("col_yellow")
        self.gridLayout_3.addWidget(self.col_yellow, 0, 5, 1, 1)
        self.col_cyan = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_cyan.sizePolicy().hasHeightForWidth())
        self.col_cyan.setSizePolicy(sizePolicy)
        self.col_cyan.setMinimumSize(QtCore.QSize(0, 15))
        self.col_cyan.setStyleSheet("background-color: cyan;\n"
"border: 0px;")
        self.col_cyan.setText("")
        self.col_cyan.setObjectName("col_cyan")
        self.gridLayout_3.addWidget(self.col_cyan, 0, 3, 1, 1)
        self.col_blue = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_blue.sizePolicy().hasHeightForWidth())
        self.col_blue.setSizePolicy(sizePolicy)
        self.col_blue.setMinimumSize(QtCore.QSize(0, 15))
        self.col_blue.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border: 0px;")
        self.col_blue.setText("")
        self.col_blue.setObjectName("col_blue")
        self.gridLayout_3.addWidget(self.col_blue, 0, 1, 1, 1)
        self.col_green = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_green.sizePolicy().hasHeightForWidth())
        self.col_green.setSizePolicy(sizePolicy)
        self.col_green.setMinimumSize(QtCore.QSize(0, 15))
        self.col_green.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_green.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border: 0px;")
        self.col_green.setText("")
        self.col_green.setObjectName("col_green")
        self.gridLayout_3.addWidget(self.col_green, 0, 2, 1, 1)
        self.col_red = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_red.sizePolicy().hasHeightForWidth())
        self.col_red.setSizePolicy(sizePolicy)
        self.col_red.setMinimumSize(QtCore.QSize(0, 15))
        self.col_red.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_red.setAutoFillBackground(False)
        self.col_red.setStyleSheet("background-color:red;\n"
"border: 0px;")
        self.col_red.setText("")
        self.col_red.setDefault(False)
        self.col_red.setFlat(False)
        self.col_red.setObjectName("col_red")
        self.gridLayout_3.addWidget(self.col_red, 0, 0, 1, 1)
        self.col_white = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_white.sizePolicy().hasHeightForWidth())
        self.col_white.setSizePolicy(sizePolicy)
        self.col_white.setMinimumSize(QtCore.QSize(0, 15))
        self.col_white.setStyleSheet("background-color: white;\n"
"border: 0px;")
        self.col_white.setText("")
        self.col_white.setObjectName("col_white")
        self.gridLayout_3.addWidget(self.col_white, 1, 1, 1, 1)
        self.col_black = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_black.sizePolicy().hasHeightForWidth())
        self.col_black.setSizePolicy(sizePolicy)
        self.col_black.setMinimumSize(QtCore.QSize(0, 15))
        self.col_black.setStyleSheet("background-color: black;\n"
"border: 0px;")
        self.col_black.setText("")
        self.col_black.setObjectName("col_black")
        self.gridLayout_3.addWidget(self.col_black, 1, 0, 1, 1)
        self.col_blue2 = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_blue2.sizePolicy().hasHeightForWidth())
        self.col_blue2.setSizePolicy(sizePolicy)
        self.col_blue2.setMinimumSize(QtCore.QSize(0, 15))
        self.col_blue2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_blue2.setStyleSheet("background-color: blue;\n"
"border: 0px;")
        self.col_blue2.setText("")
        self.col_blue2.setObjectName("col_blue2")
        self.gridLayout_3.addWidget(self.col_blue2, 1, 2, 1, 1)
        self.col_green2 = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_green2.sizePolicy().hasHeightForWidth())
        self.col_green2.setSizePolicy(sizePolicy)
        self.col_green2.setMinimumSize(QtCore.QSize(0, 15))
        self.col_green2.setStyleSheet("background-color:rgb(61, 122, 90);\n"
"border: 0px;")
        self.col_green2.setText("")
        self.col_green2.setObjectName("col_green2")
        self.gridLayout_3.addWidget(self.col_green2, 1, 3, 1, 1)
        self.col_pink = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_pink.sizePolicy().hasHeightForWidth())
        self.col_pink.setSizePolicy(sizePolicy)
        self.col_pink.setMinimumSize(QtCore.QSize(0, 15))
        self.col_pink.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_pink.setStyleSheet("background-color:rgb(255, 85, 255);\n"
"border: 0px;")
        self.col_pink.setText("")
        self.col_pink.setObjectName("col_pink")
        self.gridLayout_3.addWidget(self.col_pink, 1, 4, 1, 1)
        self.col_brown = QtWidgets.QPushButton(self.colorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_brown.sizePolicy().hasHeightForWidth())
        self.col_brown.setSizePolicy(sizePolicy)
        self.col_brown.setMinimumSize(QtCore.QSize(0, 15))
        self.col_brown.setStyleSheet("background-color: brown;\n"
"border: 0px;")
        self.col_brown.setText("")
        self.col_brown.setObjectName("col_brown")
        self.gridLayout_3.addWidget(self.col_brown, 1, 5, 1, 1)
        self.verticalLayout_11.addWidget(self.colorGrp)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.toolBox.addItem(self.page_color, "")
        self.pageShaper = QtWidgets.QWidget()
        self.pageShaper.setGeometry(QtCore.QRect(0, 0, 258, 334))
        self.pageShaper.setObjectName("pageShaper")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.pageShaper)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.labelSpace = QtWidgets.QLabel(self.pageShaper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSpace.sizePolicy().hasHeightForWidth())
        self.labelSpace.setSizePolicy(sizePolicy)
        self.labelSpace.setMaximumSize(QtCore.QSize(16777215, 100))
        self.labelSpace.setObjectName("labelSpace")
        self.verticalLayout_17.addWidget(self.labelSpace)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.spTransform = QtWidgets.QRadioButton(self.pageShaper)
        self.spTransform.setChecked(True)
        self.spTransform.setObjectName("spTransform")
        self.horizontalLayout_13.addWidget(self.spTransform)
        self.spObject = QtWidgets.QRadioButton(self.pageShaper)
        self.spObject.setObjectName("spObject")
        self.horizontalLayout_13.addWidget(self.spObject)
        self.verticalLayout_17.addLayout(self.horizontalLayout_13)
        self.resizeGrp = QtWidgets.QWidget(self.pageShaper)
        self.resizeGrp.setMinimumSize(QtCore.QSize(0, 57))
        self.resizeGrp.setObjectName("resizeGrp")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.resizeGrp)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox_3 = QtWidgets.QGroupBox(self.resizeGrp)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sizeX = QtWidgets.QCheckBox(self.groupBox_3)
        self.sizeX.setChecked(True)
        self.sizeX.setObjectName("sizeX")
        self.horizontalLayout_4.addWidget(self.sizeX)
        self.sizeY = QtWidgets.QCheckBox(self.groupBox_3)
        self.sizeY.setChecked(True)
        self.sizeY.setObjectName("sizeY")
        self.horizontalLayout_4.addWidget(self.sizeY)
        self.sizeZ = QtWidgets.QCheckBox(self.groupBox_3)
        self.sizeZ.setChecked(True)
        self.sizeZ.setObjectName("sizeZ")
        self.horizontalLayout_4.addWidget(self.sizeZ)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_resizeStep = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resizeStep.sizePolicy().hasHeightForWidth())
        self.label_resizeStep.setSizePolicy(sizePolicy)
        self.label_resizeStep.setObjectName("label_resizeStep")
        self.horizontalLayout_5.addWidget(self.label_resizeStep)
        self.sizeStepSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sizeStepSpinBox.setDecimals(1)
        self.sizeStepSpinBox.setSingleStep(0.2)
        self.sizeStepSpinBox.setProperty("value", 1.2)
        self.sizeStepSpinBox.setObjectName("sizeStepSpinBox")
        self.horizontalLayout_5.addWidget(self.sizeStepSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.resizeSlider = QtWidgets.QSlider(self.groupBox_3)
        self.resizeSlider.setMinimum(-10)
        self.resizeSlider.setMaximum(10)
        self.resizeSlider.setTracking(True)
        self.resizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.resizeSlider.setInvertedAppearance(False)
        self.resizeSlider.setInvertedControls(False)
        self.resizeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.resizeSlider.setObjectName("resizeSlider")
        self.verticalLayout_6.addWidget(self.resizeSlider)
        self.verticalLayout_16.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.resizeGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 110))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rotateGrp = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateGrp.sizePolicy().hasHeightForWidth())
        self.rotateGrp.setSizePolicy(sizePolicy)
        self.rotateGrp.setMinimumSize(QtCore.QSize(0, 80))
        self.rotateGrp.setObjectName("rotateGrp")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rotateGrp)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_angle = QtWidgets.QLabel(self.rotateGrp)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_angle.setFont(font)
        self.label_angle.setObjectName("label_angle")
        self.horizontalLayout_9.addWidget(self.label_angle)
        self.angle_box = QtWidgets.QSpinBox(self.rotateGrp)
        self.angle_box.setMaximum(360)
        self.angle_box.setSingleStep(45)
        self.angle_box.setProperty("value", 90)
        self.angle_box.setObjectName("angle_box")
        self.horizontalLayout_9.addWidget(self.angle_box)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_rotateX = QtWidgets.QPushButton(self.rotateGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateX.sizePolicy().hasHeightForWidth())
        self.btn_rotateX.setSizePolicy(sizePolicy)
        self.btn_rotateX.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateX.setStyleSheet("background-color: rgb(255, 70, 70);\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateX.setObjectName("btn_rotateX")
        self.horizontalLayout_7.addWidget(self.btn_rotateX)
        self.btn_rotateY = QtWidgets.QPushButton(self.rotateGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateY.sizePolicy().hasHeightForWidth())
        self.btn_rotateY.setSizePolicy(sizePolicy)
        self.btn_rotateY.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateY.setStyleSheet("background-color: rgb(72, 216, 0);\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateY.setObjectName("btn_rotateY")
        self.horizontalLayout_7.addWidget(self.btn_rotateY)
        self.btn_rotateZ = QtWidgets.QPushButton(self.rotateGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateZ.sizePolicy().hasHeightForWidth())
        self.btn_rotateZ.setSizePolicy(sizePolicy)
        self.btn_rotateZ.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateZ.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateZ.setObjectName("btn_rotateZ")
        self.horizontalLayout_7.addWidget(self.btn_rotateZ)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.rotateGrp)
        self.verticalLayout_16.addWidget(self.groupBox_2)
        self.btn_copyShape = QtWidgets.QPushButton(self.resizeGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_copyShape.sizePolicy().hasHeightForWidth())
        self.btn_copyShape.setSizePolicy(sizePolicy)
        self.btn_copyShape.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_copyShape.setAutoDefault(False)
        self.btn_copyShape.setObjectName("btn_copyShape")
        self.verticalLayout_16.addWidget(self.btn_copyShape)
        self.verticalLayout_17.addWidget(self.resizeGrp)
        self.toolBox.addItem(self.pageShaper, "")
        self.page_rotate = QtWidgets.QWidget()
        self.page_rotate.setGeometry(QtCore.QRect(0, 0, 258, 334))
        self.page_rotate.setObjectName("page_rotate")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_rotate)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.mirrorGrp = QtWidgets.QWidget(self.page_rotate)
        self.mirrorGrp.setObjectName("mirrorGrp")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mirrorGrp)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnMirrorX = QtWidgets.QPushButton(self.mirrorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMirrorX.sizePolicy().hasHeightForWidth())
        self.btnMirrorX.setSizePolicy(sizePolicy)
        self.btnMirrorX.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btnMirrorX.setFont(font)
        self.btnMirrorX.setStyleSheet("background-color: rgb(255, 70, 70);\n"
"color: white;\n"
"border: 0px;")
        self.btnMirrorX.setObjectName("btnMirrorX")
        self.horizontalLayout_6.addWidget(self.btnMirrorX)
        self.btn_mirrorY = QtWidgets.QPushButton(self.mirrorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mirrorY.sizePolicy().hasHeightForWidth())
        self.btn_mirrorY.setSizePolicy(sizePolicy)
        self.btn_mirrorY.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btn_mirrorY.setFont(font)
        self.btn_mirrorY.setStyleSheet("background-color: rgb(72, 216, 0);\n"
"color: white;\n"
"border: 0px;")
        self.btn_mirrorY.setObjectName("btn_mirrorY")
        self.horizontalLayout_6.addWidget(self.btn_mirrorY)
        self.btn_mirrorZ = QtWidgets.QPushButton(self.mirrorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mirrorZ.sizePolicy().hasHeightForWidth())
        self.btn_mirrorZ.setSizePolicy(sizePolicy)
        self.btn_mirrorZ.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btn_mirrorZ.setFont(font)
        self.btn_mirrorZ.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border: 0px;")
        self.btn_mirrorZ.setObjectName("btn_mirrorZ")
        self.horizontalLayout_6.addWidget(self.btn_mirrorZ)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.mirrorLRLabel = QtWidgets.QLabel(self.mirrorGrp)
        self.mirrorLRLabel.setObjectName("mirrorLRLabel")
        self.horizontalLayout_14.addWidget(self.mirrorLRLabel)
        self.mirrorLR_edit = QtWidgets.QLineEdit(self.mirrorGrp)
        self.mirrorLR_edit.setObjectName("mirrorLR_edit")
        self.horizontalLayout_14.addWidget(self.mirrorLR_edit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.verticalLayout_13.addWidget(self.mirrorGrp)
        self.toolBox.addItem(self.page_rotate, "")
        self.page_mirror = QtWidgets.QWidget()
        self.page_mirror.setGeometry(QtCore.QRect(0, 0, 258, 334))
        self.page_mirror.setObjectName("page_mirror")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_mirror)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.zero_grp = QtWidgets.QWidget(self.page_mirror)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_grp.sizePolicy().hasHeightForWidth())
        self.zero_grp.setSizePolicy(sizePolicy)
        self.zero_grp.setMinimumSize(QtCore.QSize(0, 100))
        self.zero_grp.setObjectName("zero_grp")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.zero_grp)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_suffix = QtWidgets.QLabel(self.zero_grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_suffix.sizePolicy().hasHeightForWidth())
        self.label_suffix.setSizePolicy(sizePolicy)
        self.label_suffix.setMinimumSize(QtCore.QSize(100, 0))
        self.label_suffix.setObjectName("label_suffix")
        self.horizontalLayout_10.addWidget(self.label_suffix)
        self.suffix_edit = QtWidgets.QLineEdit(self.zero_grp)
        self.suffix_edit.setObjectName("suffix_edit")
        self.horizontalLayout_10.addWidget(self.suffix_edit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.suffix_label = QtWidgets.QLabel(self.zero_grp)
        self.suffix_label.setObjectName("suffix_label")
        self.horizontalLayout_11.addWidget(self.suffix_label)
        self.suffix_keep = QtWidgets.QRadioButton(self.zero_grp)
        self.suffix_keep.setChecked(True)
        self.suffix_keep.setObjectName("suffix_keep")
        self.horizontalLayout_11.addWidget(self.suffix_keep)
        self.suffix_delete = QtWidgets.QRadioButton(self.zero_grp)
        self.suffix_delete.setObjectName("suffix_delete")
        self.horizontalLayout_11.addWidget(self.suffix_delete)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.zero_btn = QtWidgets.QPushButton(self.zero_grp)
        self.zero_btn.setObjectName("zero_btn")
        self.verticalLayout_9.addWidget(self.zero_btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.verticalLayout_12.addWidget(self.zero_grp)
        self.toolBox.addItem(self.page_mirror, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 258, 334))
        self.widget.setObjectName("widget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lineOneLiner = QtWidgets.QLineEdit(self.widget)
        self.lineOneLiner.setObjectName("lineOneLiner")
        self.verticalLayout_14.addWidget(self.lineOneLiner)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_14.addItem(spacerItem5)
        self.toolBox.addItem(self.widget, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        self.label = QtWidgets.QLabel(self.tab_control)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.tab_control)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.tabWidget.addTab(self.tab_control, "")
        self.tab_mod = QtWidgets.QWidget()
        self.tab_mod.setObjectName("tab_mod")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_mod)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.text_mod = QtWidgets.QLabel(self.tab_mod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_mod.sizePolicy().hasHeightForWidth())
        self.text_mod.setSizePolicy(sizePolicy)
        self.text_mod.setMinimumSize(QtCore.QSize(50, 0))
        self.text_mod.setObjectName("text_mod")
        self.horizontalLayout_8.addWidget(self.text_mod)
        self.combo_mod = QtWidgets.QComboBox(self.tab_mod)
        self.combo_mod.setMinimumSize(QtCore.QSize(150, 0))
        self.combo_mod.setObjectName("combo_mod")
        self.horizontalLayout_8.addWidget(self.combo_mod)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_mod, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        self.toolBox.layout().setSpacing(9)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "R.U.S.A.K.", None, -1))
        self.asJnt.setText(QtWidgets.QApplication.translate("MainWindow", "as Joint", None, -1))
        self.asCrv.setText(QtWidgets.QApplication.translate("MainWindow", "as Curve", None, -1))
        self.asReplace.setText(QtWidgets.QApplication.translate("MainWindow", "Replace", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "QuickCreate", None, -1))
        self.btn_createCtl.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_control), QtWidgets.QApplication.translate("MainWindow", "Control Creator", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_color), QtWidgets.QApplication.translate("MainWindow", "Color Picker", None, -1))
        self.labelSpace.setText(QtWidgets.QApplication.translate("MainWindow", "Space", None, -1))
        self.spTransform.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Use shape transform space", None, -1))
        self.spTransform.setText(QtWidgets.QApplication.translate("MainWindow", "Transform", None, -1))
        self.spObject.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Use object transform space", None, -1))
        self.spObject.setText(QtWidgets.QApplication.translate("MainWindow", "Object", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Resize", None, -1))
        self.sizeX.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.sizeY.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.sizeZ.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.label_resizeStep.setText(QtWidgets.QApplication.translate("MainWindow", "Step: ", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Rotate", None, -1))
        self.label_angle.setText(QtWidgets.QApplication.translate("MainWindow", "Angle:", None, -1))
        self.btn_rotateX.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.btn_rotateY.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.btn_rotateZ.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.btn_copyShape.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Replace multiple curve shapes with the last selected shape", None, -1))
        self.btn_copyShape.setText(QtWidgets.QApplication.translate("MainWindow", "Replace Shape", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageShaper), QtWidgets.QApplication.translate("MainWindow", "Shape Manipulator", None, -1))
        self.btnMirrorX.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.btn_mirrorY.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.btn_mirrorZ.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.mirrorLRLabel.setText(QtWidgets.QApplication.translate("MainWindow", "LeftName, RightName:", None, -1))
        self.mirrorLR_edit.setText(QtWidgets.QApplication.translate("MainWindow", "_L_,_R_", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_rotate), QtWidgets.QApplication.translate("MainWindow", "Mirror Transform", None, -1))
        self.label_suffix.setText(QtWidgets.QApplication.translate("MainWindow", "Suffix Name:", None, -1))
        self.suffix_edit.setText(QtWidgets.QApplication.translate("MainWindow", "_RG", None, -1))
        self.suffix_label.setText(QtWidgets.QApplication.translate("MainWindow", "Previous Suffix:", None, -1))
        self.suffix_keep.setText(QtWidgets.QApplication.translate("MainWindow", "Keep", None, -1))
        self.suffix_delete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.zero_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Zero Transform", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_mirror), QtWidgets.QApplication.translate("MainWindow", "Zero Transform", None, -1))
        self.toolBox.setItemText(self.toolBox.indexOf(self.widget), QtWidgets.QApplication.translate("MainWindow", "One Liner", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "By Fauzan Syabana", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "zansyabana@gmail.com", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_control), QtWidgets.QApplication.translate("MainWindow", "Controllers", None, -1))
        self.text_mod.setText(QtWidgets.QApplication.translate("MainWindow", "Module:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mod), QtWidgets.QApplication.translate("MainWindow", "Modules", None, -1))

#import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

