# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rusakUI.ui'
#
# Created: Fri Feb 08 11:27:43 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(272, 670)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_essential = QtGui.QWidget()
        self.tab_essential.setObjectName("tab_essential")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_essential)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.createControlGrp = QtGui.QGroupBox(self.tab_essential)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createControlGrp.sizePolicy().hasHeightForWidth())
        self.createControlGrp.setSizePolicy(sizePolicy)
        self.createControlGrp.setObjectName("createControlGrp")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.createControlGrp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(5, -1, 20, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.asJnt = QtGui.QRadioButton(self.createControlGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asJnt.sizePolicy().hasHeightForWidth())
        self.asJnt.setSizePolicy(sizePolicy)
        self.asJnt.setChecked(True)
        self.asJnt.setObjectName("asJnt")
        self.horizontalLayout.addWidget(self.asJnt)
        self.asCrv = QtGui.QRadioButton(self.createControlGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asCrv.sizePolicy().hasHeightForWidth())
        self.asCrv.setSizePolicy(sizePolicy)
        self.asCrv.setObjectName("asCrv")
        self.horizontalLayout.addWidget(self.asCrv)
        spacerItem = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox = QtGui.QGroupBox(self.createControlGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.shp_CrossArrow = QtGui.QPushButton(self.groupBox)
        self.shp_CrossArrow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_CrossArrow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_CrossArrow.setAutoFillBackground(False)
        self.shp_CrossArrow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/crossArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_CrossArrow.setIcon(icon)
        self.shp_CrossArrow.setIconSize(QtCore.QSize(20, 20))
        self.shp_CrossArrow.setCheckable(False)
        self.shp_CrossArrow.setChecked(False)
        self.shp_CrossArrow.setFlat(True)
        self.shp_CrossArrow.setObjectName("shp_CrossArrow")
        self.gridLayout.addWidget(self.shp_CrossArrow, 1, 1, 1, 1)
        self.shp_Arrow = QtGui.QPushButton(self.groupBox)
        self.shp_Arrow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Arrow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Arrow.setAutoFillBackground(False)
        self.shp_Arrow.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/arrowDouble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Arrow.setIcon(icon1)
        self.shp_Arrow.setIconSize(QtCore.QSize(20, 20))
        self.shp_Arrow.setCheckable(False)
        self.shp_Arrow.setChecked(False)
        self.shp_Arrow.setFlat(True)
        self.shp_Arrow.setObjectName("shp_Arrow")
        self.gridLayout.addWidget(self.shp_Arrow, 1, 0, 1, 1)
        self.shp_Needle = QtGui.QPushButton(self.groupBox)
        self.shp_Needle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Needle.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Needle.setAutoFillBackground(False)
        self.shp_Needle.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/needle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Needle.setIcon(icon2)
        self.shp_Needle.setIconSize(QtCore.QSize(20, 20))
        self.shp_Needle.setCheckable(False)
        self.shp_Needle.setChecked(False)
        self.shp_Needle.setFlat(True)
        self.shp_Needle.setObjectName("shp_Needle")
        self.gridLayout.addWidget(self.shp_Needle, 1, 4, 1, 1)
        self.shp_ArrowBent = QtGui.QPushButton(self.groupBox)
        self.shp_ArrowBent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_ArrowBent.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_ArrowBent.setAutoFillBackground(False)
        self.shp_ArrowBent.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/arrowBent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_ArrowBent.setIcon(icon3)
        self.shp_ArrowBent.setIconSize(QtCore.QSize(20, 20))
        self.shp_ArrowBent.setCheckable(False)
        self.shp_ArrowBent.setChecked(False)
        self.shp_ArrowBent.setFlat(True)
        self.shp_ArrowBent.setObjectName("shp_ArrowBent")
        self.gridLayout.addWidget(self.shp_ArrowBent, 1, 2, 1, 1)
        self.shp_CrossArrowBent = QtGui.QPushButton(self.groupBox)
        self.shp_CrossArrowBent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_CrossArrowBent.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_CrossArrowBent.setAutoFillBackground(False)
        self.shp_CrossArrowBent.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/crossArrowBent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_CrossArrowBent.setIcon(icon4)
        self.shp_CrossArrowBent.setIconSize(QtCore.QSize(20, 20))
        self.shp_CrossArrowBent.setCheckable(False)
        self.shp_CrossArrowBent.setChecked(False)
        self.shp_CrossArrowBent.setFlat(True)
        self.shp_CrossArrowBent.setObjectName("shp_CrossArrowBent")
        self.gridLayout.addWidget(self.shp_CrossArrowBent, 1, 3, 1, 1)
        self.shp_Circle = QtGui.QPushButton(self.groupBox)
        self.shp_Circle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Circle.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Circle.setAutoFillBackground(False)
        self.shp_Circle.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Circle.setIcon(icon5)
        self.shp_Circle.setIconSize(QtCore.QSize(20, 20))
        self.shp_Circle.setCheckable(False)
        self.shp_Circle.setChecked(False)
        self.shp_Circle.setFlat(True)
        self.shp_Circle.setObjectName("shp_Circle")
        self.gridLayout.addWidget(self.shp_Circle, 0, 0, 1, 1)
        self.shp_Square = QtGui.QPushButton(self.groupBox)
        self.shp_Square.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Square.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Square.setAutoFillBackground(False)
        self.shp_Square.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Square.setIcon(icon6)
        self.shp_Square.setIconSize(QtCore.QSize(20, 20))
        self.shp_Square.setCheckable(False)
        self.shp_Square.setChecked(False)
        self.shp_Square.setFlat(True)
        self.shp_Square.setObjectName("shp_Square")
        self.gridLayout.addWidget(self.shp_Square, 0, 1, 1, 1)
        self.shp_Cross = QtGui.QPushButton(self.groupBox)
        self.shp_Cross.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Cross.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Cross.setAutoFillBackground(False)
        self.shp_Cross.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Cross.setIcon(icon7)
        self.shp_Cross.setIconSize(QtCore.QSize(20, 20))
        self.shp_Cross.setCheckable(False)
        self.shp_Cross.setChecked(False)
        self.shp_Cross.setFlat(True)
        self.shp_Cross.setObjectName("shp_Cross")
        self.gridLayout.addWidget(self.shp_Cross, 0, 4, 1, 1)
        self.shp_Sphere = QtGui.QPushButton(self.groupBox)
        self.shp_Sphere.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Sphere.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Sphere.setAutoFillBackground(False)
        self.shp_Sphere.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/sphere.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Sphere.setIcon(icon8)
        self.shp_Sphere.setIconSize(QtCore.QSize(20, 20))
        self.shp_Sphere.setCheckable(False)
        self.shp_Sphere.setChecked(False)
        self.shp_Sphere.setFlat(True)
        self.shp_Sphere.setObjectName("shp_Sphere")
        self.gridLayout.addWidget(self.shp_Sphere, 0, 2, 1, 1)
        self.shp_Box = QtGui.QPushButton(self.groupBox)
        self.shp_Box.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shp_Box.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.shp_Box.setAutoFillBackground(False)
        self.shp_Box.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shp_Box.setIcon(icon9)
        self.shp_Box.setIconSize(QtCore.QSize(20, 20))
        self.shp_Box.setCheckable(False)
        self.shp_Box.setChecked(False)
        self.shp_Box.setFlat(True)
        self.shp_Box.setObjectName("shp_Box")
        self.gridLayout.addWidget(self.shp_Box, 0, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtGui.QComboBox(self.createControlGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.btn_createCtl = QtGui.QPushButton(self.createControlGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_createCtl.sizePolicy().hasHeightForWidth())
        self.btn_createCtl.setSizePolicy(sizePolicy)
        self.btn_createCtl.setObjectName("btn_createCtl")
        self.horizontalLayout_2.addWidget(self.btn_createCtl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.createControlGrp)
        self.colorGrp = QtGui.QGroupBox(self.tab_essential)
        self.colorGrp.setObjectName("colorGrp")
        self.gridLayout_3 = QtGui.QGridLayout(self.colorGrp)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.col_purple = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_purple.sizePolicy().hasHeightForWidth())
        self.col_purple.setSizePolicy(sizePolicy)
        self.col_purple.setMinimumSize(QtCore.QSize(0, 15))
        self.col_purple.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_purple.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border: 0px;")
        self.col_purple.setText("")
        self.col_purple.setObjectName("col_purple")
        self.gridLayout_3.addWidget(self.col_purple, 0, 4, 1, 1)
        self.col_yellow = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_yellow.sizePolicy().hasHeightForWidth())
        self.col_yellow.setSizePolicy(sizePolicy)
        self.col_yellow.setMinimumSize(QtCore.QSize(0, 15))
        self.col_yellow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_yellow.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 0px;")
        self.col_yellow.setText("")
        self.col_yellow.setObjectName("col_yellow")
        self.gridLayout_3.addWidget(self.col_yellow, 0, 5, 1, 1)
        self.col_cyan = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_cyan.sizePolicy().hasHeightForWidth())
        self.col_cyan.setSizePolicy(sizePolicy)
        self.col_cyan.setMinimumSize(QtCore.QSize(0, 15))
        self.col_cyan.setStyleSheet("background-color: cyan;\n"
"border: 0px;")
        self.col_cyan.setText("")
        self.col_cyan.setObjectName("col_cyan")
        self.gridLayout_3.addWidget(self.col_cyan, 0, 3, 1, 1)
        self.col_blue = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_blue.sizePolicy().hasHeightForWidth())
        self.col_blue.setSizePolicy(sizePolicy)
        self.col_blue.setMinimumSize(QtCore.QSize(0, 15))
        self.col_blue.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border: 0px;")
        self.col_blue.setText("")
        self.col_blue.setObjectName("col_blue")
        self.gridLayout_3.addWidget(self.col_blue, 0, 1, 1, 1)
        self.col_green = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_green.sizePolicy().hasHeightForWidth())
        self.col_green.setSizePolicy(sizePolicy)
        self.col_green.setMinimumSize(QtCore.QSize(0, 15))
        self.col_green.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_green.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border: 0px;")
        self.col_green.setText("")
        self.col_green.setObjectName("col_green")
        self.gridLayout_3.addWidget(self.col_green, 0, 2, 1, 1)
        self.col_red = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_red.sizePolicy().hasHeightForWidth())
        self.col_red.setSizePolicy(sizePolicy)
        self.col_red.setMinimumSize(QtCore.QSize(0, 15))
        self.col_red.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_red.setAutoFillBackground(False)
        self.col_red.setStyleSheet("background-color:red;\n"
"border: 0px;")
        self.col_red.setText("")
        self.col_red.setDefault(False)
        self.col_red.setFlat(False)
        self.col_red.setObjectName("col_red")
        self.gridLayout_3.addWidget(self.col_red, 0, 0, 1, 1)
        self.col_white = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_white.sizePolicy().hasHeightForWidth())
        self.col_white.setSizePolicy(sizePolicy)
        self.col_white.setMinimumSize(QtCore.QSize(0, 15))
        self.col_white.setStyleSheet("background-color: white;\n"
"border: 0px;")
        self.col_white.setText("")
        self.col_white.setObjectName("col_white")
        self.gridLayout_3.addWidget(self.col_white, 1, 1, 1, 1)
        self.col_black = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_black.sizePolicy().hasHeightForWidth())
        self.col_black.setSizePolicy(sizePolicy)
        self.col_black.setMinimumSize(QtCore.QSize(0, 15))
        self.col_black.setStyleSheet("background-color: black;\n"
"border: 0px;")
        self.col_black.setText("")
        self.col_black.setObjectName("col_black")
        self.gridLayout_3.addWidget(self.col_black, 1, 0, 1, 1)
        self.col_blue2 = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_blue2.sizePolicy().hasHeightForWidth())
        self.col_blue2.setSizePolicy(sizePolicy)
        self.col_blue2.setMinimumSize(QtCore.QSize(0, 15))
        self.col_blue2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_blue2.setStyleSheet("background-color: blue;\n"
"border: 0px;")
        self.col_blue2.setText("")
        self.col_blue2.setObjectName("col_blue2")
        self.gridLayout_3.addWidget(self.col_blue2, 1, 2, 1, 1)
        self.col_green2 = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_green2.sizePolicy().hasHeightForWidth())
        self.col_green2.setSizePolicy(sizePolicy)
        self.col_green2.setMinimumSize(QtCore.QSize(0, 15))
        self.col_green2.setStyleSheet("background-color:rgb(61, 122, 90);\n"
"border: 0px;")
        self.col_green2.setText("")
        self.col_green2.setObjectName("col_green2")
        self.gridLayout_3.addWidget(self.col_green2, 1, 3, 1, 1)
        self.col_pink = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_pink.sizePolicy().hasHeightForWidth())
        self.col_pink.setSizePolicy(sizePolicy)
        self.col_pink.setMinimumSize(QtCore.QSize(0, 15))
        self.col_pink.setFocusPolicy(QtCore.Qt.NoFocus)
        self.col_pink.setStyleSheet("background-color:rgb(255, 85, 255);\n"
"border: 0px;")
        self.col_pink.setText("")
        self.col_pink.setObjectName("col_pink")
        self.gridLayout_3.addWidget(self.col_pink, 1, 4, 1, 1)
        self.col_brown = QtGui.QPushButton(self.colorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.col_brown.sizePolicy().hasHeightForWidth())
        self.col_brown.setSizePolicy(sizePolicy)
        self.col_brown.setMinimumSize(QtCore.QSize(0, 15))
        self.col_brown.setStyleSheet("background-color: brown;\n"
"border: 0px;")
        self.col_brown.setText("")
        self.col_brown.setObjectName("col_brown")
        self.gridLayout_3.addWidget(self.col_brown, 1, 5, 1, 1)
        self.verticalLayout_4.addWidget(self.colorGrp)
        self.rotateGrp = QtGui.QGroupBox(self.tab_essential)
        self.rotateGrp.setObjectName("rotateGrp")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.rotateGrp)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_rotateX = QtGui.QPushButton(self.rotateGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateX.sizePolicy().hasHeightForWidth())
        self.btn_rotateX.setSizePolicy(sizePolicy)
        self.btn_rotateX.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateX.setStyleSheet("background-color: rgb(255, 70, 70);\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateX.setObjectName("btn_rotateX")
        self.horizontalLayout_7.addWidget(self.btn_rotateX)
        self.btn_rotateY = QtGui.QPushButton(self.rotateGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateY.sizePolicy().hasHeightForWidth())
        self.btn_rotateY.setSizePolicy(sizePolicy)
        self.btn_rotateY.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateY.setStyleSheet("background-color: rgb(72, 216, 0);\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateY.setObjectName("btn_rotateY")
        self.horizontalLayout_7.addWidget(self.btn_rotateY)
        self.btn_rotateZ = QtGui.QPushButton(self.rotateGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rotateZ.sizePolicy().hasHeightForWidth())
        self.btn_rotateZ.setSizePolicy(sizePolicy)
        self.btn_rotateZ.setMinimumSize(QtCore.QSize(0, 26))
        self.btn_rotateZ.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border: 0px;")
        self.btn_rotateZ.setObjectName("btn_rotateZ")
        self.horizontalLayout_7.addWidget(self.btn_rotateZ)
        self.verticalLayout_4.addWidget(self.rotateGrp)
        self.resizeGrp = QtGui.QGroupBox(self.tab_essential)
        self.resizeGrp.setObjectName("resizeGrp")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.resizeGrp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sizeX = QtGui.QCheckBox(self.resizeGrp)
        self.sizeX.setChecked(True)
        self.sizeX.setObjectName("sizeX")
        self.horizontalLayout_4.addWidget(self.sizeX)
        self.sizeY = QtGui.QCheckBox(self.resizeGrp)
        self.sizeY.setChecked(True)
        self.sizeY.setObjectName("sizeY")
        self.horizontalLayout_4.addWidget(self.sizeY)
        self.sizeZ = QtGui.QCheckBox(self.resizeGrp)
        self.sizeZ.setChecked(True)
        self.sizeZ.setObjectName("sizeZ")
        self.horizontalLayout_4.addWidget(self.sizeZ)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_resizeStep = QtGui.QLabel(self.resizeGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resizeStep.sizePolicy().hasHeightForWidth())
        self.label_resizeStep.setSizePolicy(sizePolicy)
        self.label_resizeStep.setObjectName("label_resizeStep")
        self.horizontalLayout_5.addWidget(self.label_resizeStep)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.resizeGrp)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setSingleStep(0.2)
        self.doubleSpinBox.setProperty("value", 1.2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        self.btn_resize = QtGui.QPushButton(self.resizeGrp)
        self.btn_resize.setObjectName("btn_resize")
        self.horizontalLayout_5.addWidget(self.btn_resize)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.resizeGrp)
        self.mirrorGrp = QtGui.QGroupBox(self.tab_essential)
        self.mirrorGrp.setObjectName("mirrorGrp")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.mirrorGrp)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnMirrorX = QtGui.QPushButton(self.mirrorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMirrorX.sizePolicy().hasHeightForWidth())
        self.btnMirrorX.setSizePolicy(sizePolicy)
        self.btnMirrorX.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btnMirrorX.setFont(font)
        self.btnMirrorX.setStyleSheet("background-color: rgb(255, 70, 70);\n"
"color: white;\n"
"border: 0px;")
        self.btnMirrorX.setObjectName("btnMirrorX")
        self.horizontalLayout_6.addWidget(self.btnMirrorX)
        self.btn_mirrorY = QtGui.QPushButton(self.mirrorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mirrorY.sizePolicy().hasHeightForWidth())
        self.btn_mirrorY.setSizePolicy(sizePolicy)
        self.btn_mirrorY.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btn_mirrorY.setFont(font)
        self.btn_mirrorY.setStyleSheet("background-color: rgb(72, 216, 0);\n"
"color: white;\n"
"border: 0px;")
        self.btn_mirrorY.setObjectName("btn_mirrorY")
        self.horizontalLayout_6.addWidget(self.btn_mirrorY)
        self.btn_mirrorZ = QtGui.QPushButton(self.mirrorGrp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mirrorZ.sizePolicy().hasHeightForWidth())
        self.btn_mirrorZ.setSizePolicy(sizePolicy)
        self.btn_mirrorZ.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.btn_mirrorZ.setFont(font)
        self.btn_mirrorZ.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border: 0px;")
        self.btn_mirrorZ.setObjectName("btn_mirrorZ")
        self.horizontalLayout_6.addWidget(self.btn_mirrorZ)
        self.verticalLayout_4.addWidget(self.mirrorGrp)
        self.oneLinerGrp = QtGui.QGroupBox(self.tab_essential)
        self.oneLinerGrp.setObjectName("oneLinerGrp")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.oneLinerGrp)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.oneLinerEdit = QtGui.QLineEdit(self.oneLinerGrp)
        self.oneLinerEdit.setObjectName("oneLinerEdit")
        self.verticalLayout_6.addWidget(self.oneLinerEdit)
        self.verticalLayout_4.addWidget(self.oneLinerGrp)
        self.tabWidget.addTab(self.tab_essential, "")
        self.tab_mod = QtGui.QWidget()
        self.tab_mod.setObjectName("tab_mod")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_mod)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.text_mod = QtGui.QLabel(self.tab_mod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_mod.sizePolicy().hasHeightForWidth())
        self.text_mod.setSizePolicy(sizePolicy)
        self.text_mod.setMinimumSize(QtCore.QSize(50, 0))
        self.text_mod.setObjectName("text_mod")
        self.horizontalLayout_8.addWidget(self.text_mod)
        self.combo_mod = QtGui.QComboBox(self.tab_mod)
        self.combo_mod.setMinimumSize(QtCore.QSize(150, 0))
        self.combo_mod.setObjectName("combo_mod")
        self.horizontalLayout_8.addWidget(self.combo_mod)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.widget = QtGui.QWidget(self.tab_mod)
        self.widget.setMinimumSize(QtCore.QSize(0, 500))
        self.widget.setObjectName("widget")
        self.verticalLayout_8.addWidget(self.widget)
        self.tabWidget.addTab(self.tab_mod, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 272, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "R.U.S.A.K.", None, QtGui.QApplication.UnicodeUTF8))
        self.createControlGrp.setTitle(QtGui.QApplication.translate("MainWindow", "Control Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.asJnt.setText(QtGui.QApplication.translate("MainWindow", "as Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.asCrv.setText(QtGui.QApplication.translate("MainWindow", "as Curve", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "QuickCreate", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_createCtl.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.colorGrp.setTitle(QtGui.QApplication.translate("MainWindow", "Color Picker", None, QtGui.QApplication.UnicodeUTF8))
        self.rotateGrp.setTitle(QtGui.QApplication.translate("MainWindow", "Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_rotateX.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_rotateY.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_rotateZ.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.resizeGrp.setTitle(QtGui.QApplication.translate("MainWindow", "Resize", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeX.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeY.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeZ.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_resizeStep.setText(QtGui.QApplication.translate("MainWindow", "Step: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_resize.setText(QtGui.QApplication.translate("MainWindow", "Resize", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorGrp.setTitle(QtGui.QApplication.translate("MainWindow", "Mirror Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMirrorX.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mirrorY.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mirrorZ.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.oneLinerGrp.setTitle(QtGui.QApplication.translate("MainWindow", "OneLiner Renamer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_essential), QtGui.QApplication.translate("MainWindow", "Essentials", None, QtGui.QApplication.UnicodeUTF8))
        self.text_mod.setText(QtGui.QApplication.translate("MainWindow", "Module:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mod), QtGui.QApplication.translate("MainWindow", "Modules", None, QtGui.QApplication.UnicodeUTF8))

# import icons_rc
